//! Build-time linker-script generator. It parses the SoC device tree with the
//! shared `dtree` reader. It emits the linker script whose addresses come from
//! the same description the firmware boots with. This way build.zig does not
//! hand-roll a flattened-tree parser.
//!
//! Usage: fdt-ld <dtb-path> <kind:main|fsbl|arm64-main> <out-path> [region-hex]
//!   main : firmware image linked at the DRAM /memory base.
//!   fsbl : XIP first-stage. It puts .text/.rodata in the SPI-NOR flash window.
//!          It puts .data/.bss/stack in the DRAM window (region-hex bytes). The
//!          .data load image stays in flash. creek has no SRAM, so DRAM is the
//!          only writable RAM.
//!   arm64-main : the AArch64 -bios image. It XIPs .text/.rodata from the
//!          pflash0 window (cfi-flash node in the tree; QEMU aarch64 virt maps
//!          -bios at address 0 and resets there) and keeps .data/.bss/stack in
//!          the DRAM /memory window.

const std = @import("std");
const dtree = @import("dtree");
const fdt_bases = @import("fdt_bases");
const Bases = fdt_bases.Bases;

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const gpa = init.gpa;

    var args = try init.minimal.args.iterateAllocator(gpa);
    defer args.deinit();
    _ = args.skip(); // zippy:ignore discarded_error -- the tool ignores the program name arg
    const dtb_path = args.next() orelse return error.Usage;
    const kind = args.next() orelse return error.Usage;
    const out_path = args.next() orelse return error.Usage;
    const region_str = args.next(); // optional (fsbl only)

    var bases: Bases = .{};

    if (dtb_path.len != 0) {
        const file = if (std.fs.path.isAbsolute(dtb_path))
            try std.Io.Dir.openFileAbsolute(io, dtb_path, .{})
        else
            try std.Io.Dir.cwd().openFile(io, dtb_path, .{});
        defer file.close(io);
        const fdt = try dtree.Reader.initFile(gpa, io, file);
        defer fdt.deinit();
        fdt_bases.parse(&fdt, &bases);
    }

    const script = if (std.mem.eql(u8, kind, "fsbl")) blk: {
        const region: u64 = if (region_str) |s| try std.fmt.parseInt(u64, s, 0) else 0x4000;
        // Use on-chip SRAM for the FSBL scratch when the tree has it. The FSBL
        // then runs its stack/.data/.bss from SRAM. It never reads DRAM before
        // it brings DDR up and read-trains it. Without SRAM (legacy creek), use
        // the top of the DRAM window instead. The FSBL scratch must not sit at
        // the RAM base. There main Weir's bottom-loaded image copy overwrites
        // the FSBL's own live stack and console mid-flight. That corrupts the
        // FSBL silently.
        var origin = bases.ram_base + bases.ram_size - region;
        var len = region;
        if (bases.sram_size != 0) {
            origin = bases.sram_base;
            len = bases.sram_size;
        }
        // The FSBL runs XIP from the `river-fsbl` partition. Its flash origin is
        // flash_base + fsbl_off, which clears the fpga-bitstream slot. The main
        // image offset and max come from the `river-firmware` partition. The
        // script lowers them to the _fsbl_main_offset/_max absolute symbols.
        break :blk try std.fmt.allocPrint(gpa, fsbl_template, .{
            bases.flash_base + bases.fsbl_off, origin, len, bases.fw_off, bases.fw_max,
        });
    } else if (std.mem.eql(u8, kind, "arm64-main")) blk: {
        // The AArch64 -bios image. QEMU's aarch64 virt maps -bios into the
        // pflash0 window and resets there, so .text/.rodata run in place from
        // FLASH while .data/.bss/stack live in the /memory RAM the tree
        // declares. The reset entry copies .data and zeroes .bss before it
        // touches globals, the same way the FSBL does.
        const flash_len: u64 = if (bases.flash_size != 0) bases.flash_size else 0x04000000;
        break :blk try std.fmt.allocPrint(gpa, arm64_main_template, .{
            bases.flash_base, flash_len, bases.ram_base, bases.ram_size,
        });
    } else try std.fmt.allocPrint(gpa, main_template, .{bases.ram_base});

    const out = if (std.fs.path.isAbsolute(out_path))
        try std.Io.Dir.createFileAbsolute(io, out_path, .{})
    else
        try std.Io.Dir.cwd().createFile(io, out_path, .{});
    defer out.close(io);
    try out.writeStreamingAll(io, script);
}

const main_template =
    \\/* Generated by tools/fdt_ld.zig from the SoC device tree. This is the
    \\ * firmware image layout for RISC-V. The loader puts it at the start of RAM
    \\ * in M-mode. Reset enters at _start. */
    \\ENTRY(_start)
    \\RAM_BASE = 0x{x};
    \\STACK_SIZE = 0x10000; /* 64 KiB per hart. It must stay 1 << 16. See start.zig. */
    \\MAX_HARTS = 8;
    \\SECTIONS
    \\{{
    \\    . = RAM_BASE;
    \\    .text : {{ KEEP(*(.text.boot)) *(.text .text.*) }}
    \\    . = ALIGN(8);
    \\    .rodata : {{ *(.rodata .rodata.* .srodata .srodata.*) }}
    \\    . = ALIGN(8);
    \\    __rodata_end = .;
    \\    .data : {{ PROVIDE(__global_pointer$ = . + 0x800); *(.data .data.* .sdata .sdata.*) }}
    \\    . = ALIGN(8);
    \\    .bss (NOLOAD) : {{
    \\        __bss_start = .; *(.bss .bss.* .sbss .sbss.* COMMON)
    \\        . = ALIGN(8); __bss_end = .;
    \\    }}
    \\    . = ALIGN(16);
    \\    .noinit (NOLOAD) : {{ *(.noinit .noinit.*) }}
    \\    . = ALIGN(16);
    \\    _stacks_bottom = .;
    \\    . = . + STACK_SIZE * MAX_HARTS;
    \\    _stacks_top = .;
    \\    /DISCARD/ : {{
    \\        *(.comment) *(.note .note.*) *(.eh_frame .eh_frame_hdr) *(.riscv.attributes)
    \\    }}
    \\}}
    \\
;

const arm64_main_template =
    \\/* Generated by tools/fdt_ld.zig from the device tree. This is the AArch64
    \\ * -bios image layout. QEMU's aarch64 virt maps -bios into pflash0 at
    \\ * address 0 and resets there, so .text/.rodata run in place from FLASH.
    \\ * .data/.bss/stack live in the RAM window the tree's /memory node gives. */
    \\ENTRY(_start)
    \\MEMORY
    \\{{
    \\    FLASH (rx)  : ORIGIN = 0x{x}, LENGTH = 0x{x}
    \\    RAM   (rwx) : ORIGIN = 0x{x}, LENGTH = 0x{x}
    \\}}
    \\SECTIONS
    \\{{
    \\    .text : {{ KEEP(*(.text.boot)) *(.text .text.*) }} > FLASH
    \\    . = ALIGN(0x800);
    \\    .vectors : {{ KEEP(*(.vectors)) }} > FLASH
    \\    . = ALIGN(16);
    \\    .rodata : {{ *(.rodata .rodata.* .srodata .srodata.*) }} > FLASH
    \\    . = ALIGN(16);
    \\    .data : {{
    \\        *(.data .data.* .sdata .sdata.*)
    \\        *(.got .got.* .got.plt)
    \\    }} > RAM AT> FLASH
    \\    _data_lma = LOADADDR(.data);
    \\    _data_vma = ADDR(.data);
    \\    _data_end = _data_vma + SIZEOF(.data);
    \\    .bss (NOLOAD) : {{
    \\        __bss_start = .; *(.bss .bss.* .sbss .sbss.* COMMON);
    \\        . = ALIGN(16); __bss_end = .;
    \\    }} > RAM
    \\    /DISCARD/ : {{
    \\        *(.comment) *(.note .note.*) *(.eh_frame .eh_frame_hdr)
    \\    }}
    \\}}
    \\_stack_top = ORIGIN(RAM) + LENGTH(RAM);
    \\
;

const fsbl_template =
    \\/* Generated by tools/fdt_ld.zig from the SoC device tree. This is the XIP
    \\ * first-stage layout. .text/.rodata run in place from the SPI-NOR flash
    \\ * window. The writable .data/.bss and the stack live in the DRAM window.
    \\ * The dcache backs it as scratch until the FSBL brings DDR up. The .data
    \\ * load image is in flash and _start copies it. creek has no SRAM, so DRAM
    \\ * is the only writable RAM. */
    \\ENTRY(_start)
    \\MEMORY
    \\{{
    \\    FLASH (rx)  : ORIGIN = 0x{x}, LENGTH = 0x100000
    \\    RAM   (rwx) : ORIGIN = 0x{x}, LENGTH = 0x{x}
    \\}}
    \\SECTIONS
    \\{{
    \\    .text : {{ KEEP(*(.text.boot)) *(.text .text.*) }} > FLASH
    \\    .rodata : {{ *(.rodata .rodata.* .srodata .srodata.*) }} > FLASH
    \\    .data : {{
    \\        PROVIDE(__global_pointer$ = . + 0x800); *(.data .data.* .sdata .sdata.*)
    \\    }} > RAM AT> FLASH
    \\    _data_lma = LOADADDR(.data);
    \\    _data_vma = ADDR(.data);
    \\    _data_end = _data_vma + SIZEOF(.data);
    \\    .bss (NOLOAD) : {{
    \\        __bss_start = .; *(.bss .bss.* .sbss .sbss.* COMMON);
    \\        . = ALIGN(8); __bss_end = .;
    \\    }} > RAM
    \\    /DISCARD/ : {{
    \\        *(.comment) *(.note .note.*) *(.eh_frame .eh_frame_hdr) *(.riscv.attributes)
    \\    }}
    \\}}
    \\_stack_top = ORIGIN(RAM) + LENGTH(RAM);
    \\/* Main-image flash layout from the `river-firmware` DT partition. Absolute
    \\ * symbols: config.zig reads their ADDRESS as the value (no build flag). */
    \\_fsbl_main_offset = 0x{x};
    \\_fsbl_main_max = 0x{x};
    \\
;
